const config = {
  VERSION: process.env.VERSION
};

export default config;

export const SERVER_API_URL = process.env.SERVER_API_URL;

export const AUTHORITIES = {
  ADMIN: 'ROLE_ADMIN',
  USER: 'ROLE_USER',
  PERSON_READ: 'ROLE_PERSON_READ',
  PERSON_SAVE: 'ROLE_PERSON_SAVE',
  PERSON_DELETE: 'ROLE_PERSON_DELETE',
  PERSON_CREATE: 'ROLE_PERSON_CREATE',
  PRODUCT_READ: 'ROLE_PRODUCT_READ',
  PRODUCT_SAVE: 'ROLE_PRODUCT_SAVE',
  PRODUCT_DELETE: 'ROLE_PRODUCT_DELETE',
  PRODUCT_CREATE: 'ROLE_PRODUCT_CREATE',
  INGREDIENT_READ: 'ROLE_INGREDIENT_READ',
  INGREDIENT_SAVE: 'ROLE_INGREDIENT_SAVE',
  INGREDIENT_DELETE: 'ROLE_INGREDIENT_DELETE',
  INGREDIENT_CREATE: 'ROLE_INGREDIENT_CREATE',
  CATEGORY_READ: 'ROLE_CATEGORY_READ',
  CATEGORY_SAVE: 'ROLE_CATEGORY_SAVE',
  CATEGORY_DELETE: 'ROLE_CATEGORY_DELETE',
  CATEGORY_CREATE: 'ROLE_CATEGORY_CREATE',
  RECIPE_READ: 'ROLE_RECIPE_READ',
  RECIPE_SAVE: 'ROLE_RECIPE_SAVE',
  RECIPE_DELETE: 'ROLE_RECIPE_DELETE',
  RECIPE_CREATE: 'ROLE_RECIPE_CREATE',
  TASK_READ: 'ROLE_TASK_READ',
  TASK_SAVE: 'ROLE_TASK_SAVE',
  TASK_DELETE: 'ROLE_TASK_DELETE',
  TASK_CREATE: 'ROLE_TASK_CREATE'
};

export const messages = {
  DATA_ERROR_ALERT: 'Internal Error'
};

export const APP_DATE_FORMAT = 'DD/MM/YY HH:mm';
export const APP_TIMESTAMP_FORMAT = 'DD/MM/YY HH:mm:ss';
export const APP_LOCAL_DATE_FORMAT = 'DD/MM/YYYY';
export const APP_LOCAL_DATETIME_FORMAT = 'YYYY-MM-DDTHH:mm';
export const APP_LOCAL_DATETIME_FORMAT_Z = 'YYYY-MM-DDTHH:mm Z';
export const APP_WHOLE_NUMBER_FORMAT = '0,0';
export const APP_TWO_DIGITS_AFTER_POINT_NUMBER_FORMAT = '0,0.[00]';
