spring:
  config:
    activate:
      on-profile: prod
  sleuth:
    sampler:
      probability: 0.1
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWKS_URL:https://spendingbetter.com/.well-known/jwks.json}

com:
  microservice:
    authentication:
      jwt:
        key-store: ${KEYSTORE:}
        key-store-password: ${KEYSTORE_PASSWORD:}
        key-alias: ${KEYSTORE_ALIAS:}
      user-info-uri: ${USER_INFO_URI:https://spendingbetter.com/auth/api/authenticatedUser}
