spring:
    application:
        name: user-service
    main:
        allow-bean-definition-overriding: true

management:
    endpoints:
        web:
            exposure:
                include: '*'
            cors:
                allowed-origins: '*'
                allow-credentials: false
    tracing:
        propagation:
            produce: w3c, b3, b3_multi
            consume: b3, w3c, b3_multi
        baggage:
            remote-fields: requestId
            correlation:
                fields: requestId

logging:
    pattern:
        level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-},requestId=%X{requestId:-}]"

---
spring:
    config:
        activate:
            on-profile: consul
        import: consul:${consul_url:localhost:8500}
    cloud:
        consul:
            config:
                fail-fast: ${FAIL_FAST:true}
                format: yaml
    autoconfigure:
        exclude: org.springframework.cloud.consul.config.ConsulConfigAutoConfiguration