apiVersion: v1
kind: Service
metadata:
  name: quarkus-service
#  annotations:
#    cloud.google.com/app-protocols: '{"https-port":"HTTPS","http-port":"HTTP"}'
  labels:
    app: quarkus-service
spec:
  ports:
#    - name: https-port
#      port: 8443
    - name: http-port
      port: 8085
  selector:
    app: quarkus
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quarkus-service
spec:
  selector:
    matchLabels:
      app: quarkus-service
  replicas: 1
  template:
    metadata:
      labels:
        app: quarkus-service
        version: v1
    spec:
      containers:
        - name: quarkus-service
          image: quarkus-service:0.0.1-SNAPSHOT
          resources:
            requests:
              memory: "256Mi"
            limits:
              memory: "512Mi"
          volumeMounts:
            - name: spendingbetter-pub-key
              mountPath: "/etc/ssl_certs_pub"
              readOnly: true
          env:
            - name: JAVA_OPTS
              value: -Xms256m -Xmx512m
            - name: QUARKUS_HTTP_PORT
              value: "8085"
            - name: QUARKUS_PROFILES
              value: prod
            - name: MONGODB_URI
              value: mongodb://mongodb:27017
            - name: MONGODB_DATABASE
              value: docker
            - name: PUBLIC_KEY_PATH
              value: /etc/ssl_certs_pub/www.spendingbetter.com.pub
            - name: QUARKUS_METRICS_PATH
              value: /actuator
          ports:
            - containerPort: 8085
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /actuator/health
              port: 8085
            initialDelaySeconds: 200
            periodSeconds: 5
      volumes:
        - name: spendingbetter-pub-key
          secret:
            secretName: spendingbetter-pub-key
