apiVersion: v1
kind: Service
metadata:
  name: admin-server
  annotations:
    cloud.google.com/app-protocols: '{"https-port":"HTTPS","http-port":"HTTP"}'
  labels:
    app: admin-server
spec:
  ports:
    - name: https-port
      port: 8443
    - name: http-port
      port: 9000
  selector:
    app: admin-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-server
spec:
  selector:
    matchLabels:
      app: admin-server
  replicas: 1
  template:
    metadata:
      labels:
        app: admin-server
        version: v1
    spec:
      containers:
        - name: admin-server
          image: fielcapao/microservices-design-patterns-admin-service:latest
          resources:
            requests:
              memory: "256Mi"
            limits:
              memory: "512Mi"
          env:
            - name: JAVA_OPTS
              value: -Xms256m -Xm512m
            - name: SERVER_PORT
              value: "9000"
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              value: "true"
            - name: SPRING_DATA_MONGODB_URI
              value: mongodb://mongodb:27017
            - name: SPRING_DATA_MONGODB_DATABASE
              value: docker
            - name: SPRING_REDIS_HOST
              value: redis
            - name: OAUTH_CLIENT_ID
              value: actuator
            - name: OAUTH_CLIENT_SECRET
              value: actuator_password
            - name: SPRING_BOOT_ADMIN_CONTEXT_PATH
              value: /monitoring
            - name: SERVER_SERVLET_CONTEXT_PATH
              value: /monitoring
            - name: SERVER_USE_FORWARD_HEADERS
              value: "true"
            - name: SPRING_CLOUD_CONSUL_ENABLED
              value: "false"
            - name: OPENTRACING_JAEGER_ENABLED
              value: "false"
            - name: SPRING_CLOUD_KUBERNETES_CONFIG_NAMESPACE
              value: "default"
#            - name: ACCESS_TOKEN_URI
#              value: https://YOUR_DOMAIN.com/auth/oauth/token
#            - name: AUTHORIZATION_URL
#              value: https://YOUR_DOMAIN.com/auth/oauth/authorize
#            - name: USER_INFO_URI
#              value: https://YOUR_DOMAIN.com/auth/api/authenticatedUser
          ports:
            - containerPort: 9000
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /monitoring/actuator/health
              port: 9000
            initialDelaySeconds: 1000
            periodSeconds: 5
