apiVersion: v1
kind: Service
metadata:
  name: edge-server
  annotations:
    cloud.google.com/app-protocols: '{"https-port":"HTTPS","http-port":"HTTP"}'
  labels:
    app: edge-server
spec:
  ports:
    - name: https-port
      port: 8443
    - name: http-port
      port: 8080
  selector:
    app: edge-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-server
spec:
  selector:
    matchLabels:
      app: edge-server
  replicas: 1
  template:
    metadata:
      labels:
        app: edge-server
        version: v1
    spec:
      containers:
        - name: edge-server
          image: edge-server:0.0.1-SNAPSHOT #edge-server:0.0.1-SNAPSHOT
          resources:
            requests:
              memory: "256Mi"
            limits:
              memory: "512Mi"
          volumeMounts:
            - name: spendingbetter-pub-key
              mountPath: "/etc/ssl_certs_pub"
              readOnly: true
            - name: spendingbetter-jks
              mountPath: "/etc/ssl_certs"
              readOnly: true
          env:
            - name: JAVA_OPTS
              value: -Xss256K -Xms1M -XX:+UseSerialGC -Djava.compiler=none -XX:ReservedCodeCacheSize=2496k -XX:MaxDirectMemorySize=1M #-Xms256m -Xmx512m
            - name: SERVER_PORT
              value: "8080"
            - name: SPRING_PROFILES_ACTIVE
              value: auth,prod
            - name: SPRING_DATA_MONGODB_URI
              value: mongodb://192.168.1.5:27017
            - name: SPRING_DATA_MONGODB_DATABASE
              value: docker
            - name: SPRING_REDIS_HOST
              value: 192.168.1.5
            - name: SPRING_CLOUD_CONSUL_ENABLED
              value: "false"
            - name: OPENTRACING_JAEGER_ENABLED
              value: "false"
            - name: SPRING_CLOUD_KUBERNETES_CONFIG_NAMESPACE
              value: "default"
            - name: SPRING_MAIN_WEB_APPLICATION_TYPE
              value: "reactive"
            - name: SPRING_MAIN_ALLOW_CIRCULAR_REFERENCES
              value: "true"
            - name: MANAGEMENT_ENDPOINTS_WEB_CORS_ALLOW_CREDENTIALS
              value: "false"
            - name: KEYSTORE_PASSWORD
              value: Cert202!
            - name: KEYSTORE
              value: file:/etc/ssl_certs/www.spendingbetter.com.jks
#            - name: KEYSTORE
#              value: file:/etc/ssl_certs_pub/www.spendingbetter.com.pub
            - name: KEYSTORE_ALIAS
              value: spendingbetter
#            - name: COM_MICROSERVICE_AUTHENTICATION_JWT_ENABLED_PUBLIC_KEY
#              value: "true"
#            - name: SPRING_CLOUD_GATEWAY_DISCOVERY_LOCATOR_ENABLED
#              value: "true"
            - name: LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_CLOUD_GATEWAY
              value: "trace"
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 1000
            periodSeconds: 5
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 1000
      volumes:
        - name: spendingbetter-pub-key
          secret:
            secretName: spendingbetter-pub-key
        - name: spendingbetter-jks
          secret:
            secretName: spendingbetter-jks
