apiVersion: v1
kind: Service
metadata:
  name: python-service
  annotations:
    cloud.google.com/app-protocols: '{"https-port":"HTTPS","http-port":"HTTP"}'
  labels:
    app: python-service
spec:
  ports:
    - name: https-port
      port: 8443
    - name: http-port
      port: 3005
  selector:
    app: python-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-service
spec:
  selector:
    matchLabels:
      app: python-service
  replicas: 1
  template:
    metadata:
      labels:
        app: python-service
        version: v1
    spec:
      containers:
        - name: python-service
          image: docker_receipt-api:latest
          imagePullPolicy: Never
          resources:
            requests:
              memory: "256Mi"
#              cpu: "30m"
            limits:
              memory: "512Mi"
#              cpu: "30m"
          env:
            - name: SERVER_PORT
              value: "3005"
            - name: SPRING_PROFILES_ACTIVE
              value: kubernetes,dev
            - name: MONGODB_URI
              value: mongodb://mongodb:27017/docker
            - name: UPLOAD_FOLDER
              value: /tmp
            - name: ENV_FILE_LOCATION
              value: ./.env
#            - name: JWT_ALGORITHM
#              value: RS256
            - name: LOG_LEVEL
              value: TRACE
          ports:
            - containerPort: 3005
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /actuator/health
              port: 3005
            initialDelaySeconds: 1000
            periodSeconds: 5
