#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name:  mongo-persistent-storage
#spec:
#  accessModes:
#    - ReadWriteOnce
#  volumeMode: Filesystem
#  resources:
#    requests:
#      storage: 1Gi
#---
#apiVersion: storage.k8s.io/v1
#kind: StorageClass
#metadata:
#  name: demo
#provisioner: microk8s.io/hostpath
#reclaimPolicy: Delete
#volumeBindingMode: Immediate
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  labels:
    appdb: mongodb
spec:
#  serviceName: "mongo"
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      appdb: mongodb
  template:
    metadata:
      labels:
        appdb: mongodb
    spec:
      containers:
        - name: mongodb
          image: arm64v8/mongo:4.4.8
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "100m"
          ports:
            - containerPort: 27017
#          volumeMounts:
#            - name: mongo-persistent-storage
#              mountPath: /data/db
      restartPolicy: Always
#      volumes:
#        - name: mongo-persistent-storage
#          persistentVolumeClaim:
#            claimName: mongo-persistent-storage
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  ports:
  - port: 27017
    targetPort: 27017
  clusterIP: None
  selector:
    appdb: mongodb
