apiVersion: v1
kind: Service
metadata:
  name: go-service
  annotations:
    cloud.google.com/app-protocols: '{"https-port":"HTTPS","http-port":"HTTP"}'
  labels:
    app: go-service
spec:
  ports:
    - name: https-port
      port: 8443
    - name: http-port
      port: 3006
  selector:
    app: go-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-service
  labels:
    app: go-service
spec:
  selector:
    matchLabels:
      app: go-service
  replicas: 1
  template:
    metadata:
      labels:
        app: go-service
    spec:
      containers:
        - name: go-service
          image: docker_post-api:latest
          imagePullPolicy: Never
          resources:
            requests:
              memory: "256Mi"
            limits:
              memory: "512Mi"
          env:
            - name: SERVER_PORT
              value: "3006"
            - name: SPRING_PROFILES_ACTIVE
              value: kubernetes
            - name: MONGODB_URI
              value: mongodb://mongodb:27017
            - name: MONGODB_DATABASE
              value: docker
            - name: LOG_LEVEL
              value: TRACE
          ports:
            - containerPort: 3006
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /actuator/health
              port: 3006
            initialDelaySeconds: 1000
            periodSeconds: 5
