apiVersion: v1
kind: Service
metadata:
  name: person-service
#  annotations:
#    cloud.google.com/app-protocols: '{"https-port":"HTTPS","http-port":"HTTP"}'
  labels:
    app: person-service
spec:
  ports:
#    - name: https-port
#      port: 8443
    - name: http-port
      port: 8082
  selector:
    app: person-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: person-service
spec:
  selector:
    matchLabels:
      app: person-service
  replicas: 1
  template:
    metadata:
      labels:
        app: person-service
        version: v1
    spec:
      containers:
        - name: person-service
          image: person-service:latest #fielcapao/microservices-design-patterns-person-service:latest #eu.gcr.io/api-project-646370370811/person-service:b3f4981bef4970e146539962f15514bfd1afff7f
          imagePullPolicy: Never
          resources:
            requests:
              memory: "256Mi"
            limits:
              memory: "512Mi"
          env:
            - name: JAVA_OPTS
              value: --enable-preview -Xss256K -Xms1M -XX:+UseSerialGC -Djava.compiler=none -XX:ReservedCodeCacheSize=2496k -XX:MaxDirectMemorySize=1M
            - name: SERVER_PORT
              value: "8082"
            - name: SPRING_PROFILES_ACTIVE
              value: dev,callPostApi,kafka
            - name: SPRING_DATA_MONGODB_URI
              value: mongodb://mongodb:27017/docker
            - name: SPRING_DATA_MONGODB_DATABASE
              value: docker
            - name: SPRING_MAIN_ALLOW_BEAN_DEFINITION_OVERRIDING
              value: "true"
            - name: SPRING_CLOUD_CONSUL_ENABLED
              value: "false"
            - name: OPENTRACING_JAEGER_ENABLED
              value: "false"
            - name: SPRING_CLOUD_KUBERNETES_CONFIG_NAMESPACE
              value: "default"
            - name: SPRING_CLOUD_KUBERNETES_CONFIG_NAME
              value: "person-service"
            - name: MANAGEMENT_ENDPOINTS_WEB_CORS_ALLOW_CREDENTIALS
              value: "false"
            - name: SPRING_MAIN_ALLOW_CIRCULAR_REFERENCES
              value: "true"
            - name: LOGGING_LEVEL_COM_MICROSERVICE
              value: trace
#            - name: LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_CLOUD
#              value: trace
#            - name: LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY
#              value: trace
#            - name: LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_KAFKA
#              value: trace
#            - name: LOGGING_LEVEL_ORG_APACHE_COYOTE_HTTP11
#              value: trace
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092
            - name: SPRING_KAFKA_CONSUMER_AUTO_OFFSET_RESET
              value: latest
            - name: KAFKA_LOCAL_TEST_ENABLED
              value: "true"
            - name: PRODUCER_ENABLED
              value: "false"
#            - name: SPRING_CONFIG_IMPORT
#              value: "kubernetes:"
            - name: COM_MICROSERVICE_AUTHENTICATION_JWT_KEY_VALUE
              value: YTMwOTIwODE1MGMzOGExM2E4NDc5ZjhjMmQwMTdkNDJlZWZkOTE0YTMwNWUxMTgxMTFhZTI1ZDI3M2QyMTRmMjI5Yzg0ODBjYTUxYjVkY2I5ZmY0YmRkMzBlZjRjNDM2Y2NiYzhlZjQ0ODRjMWZlNzVmZjdjM2JiMjdkMjdmMjk=
          ports:
            - containerPort: 8082
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /actuator/health/liveness
              port: 8082
            initialDelaySeconds: 1000
            periodSeconds: 5
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /actuator/health/readiness
              port: 8082
            initialDelaySeconds: 1000
            periodSeconds: 5
