apiVersion: v1
kind: Service
metadata:
  name: kotlin-service
  annotations:
    cloud.google.com/app-protocols: '{"https-port":"HTTPS","http-port":"HTTP"}'
  labels:
    app: kotlin-service
spec:
  ports:
    - name: https-port
      port: 8443
    - name: http-port
      port: 9092
  selector:
    app: kotlin-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kotlin-service
  labels:
    app: kotlin-service
spec:
  selector:
    matchLabels:
      app: kotlin-service
  replicas: 1
  template:
    metadata:
      labels:
        app: kotlin-service
    spec:
      containers:
        - name: kotlin-service
          image: user-service:0.0.1-SNAPSHOT #fielcapao/microservices-design-patterns-kotlin-service:latest
          resources:
            requests:
              memory: "256Mi"
            limits:
              memory: "512Mi"
          volumeMounts:
              - name: spendingbetter-pub-key
                mountPath: "/etc/ssl_certs_pub"
                readOnly: true
          env:
            - name: JAVA_OPTS
              value: -Xss256K -Xms1M -XX:+UseSerialGC -Djava.compiler=none -XX:ReservedCodeCacheSize=2496k -XX:MaxDirectMemorySize=1M #-Xms256m -Xmx512m
            - name: SERVER_PORT
              value: "9092"
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: SPRING_DATA_MONGODB_URI
              value: mongodb://mongo:27017
            - name: SPRING_DATA_MONGODB_DATABASE
              value: docker
            - name: SPRING_CLOUD_CONSUL_ENABLED
              value: "false"
            - name: OPENTRACING_JAEGER_ENABLED
              value: "false"
            - name: SPRING_CLOUD_KUBERNETES_CONFIG_NAMESPACE
              value: "default"
            - name: MANAGEMENT_ENDPOINTS_WEB_CORS_ALLOW_CREDENTIALS
              value: "false"
            - name: SPRING_MAIN_ALLOW_CIRCULAR_REFERENCES
              value: "true"
            - name: KEYSTORE_PASSWORD
              value: Cert202!
            - name: KEYSTORE
              value: file:/etc/ssl_certs_pub/www.spendingbetter.com.pub
            - name: KEYSTORE_ALIAS
              value: spendingbetter
            - name: COM_MICROSERVICE_AUTHENTICATION_JWT_ENABLED_PUBLIC_KEY
              value: "true"
            - name: LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB
              value: trace
            - name: LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY
              value: trace
          ports:
            - containerPort: 9092
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /actuator/health
              port: 9092
            initialDelaySeconds: 1000
            periodSeconds: 5
          readinessProbe:
              httpGet:
                  scheme: HTTP
                  path: /actuator/health/readiness
                  port: 9092
              initialDelaySeconds: 1000
              periodSeconds: 5
      volumes:
          - name: spendingbetter-pub-key
            secret:
                secretName: spendingbetter-pub-key
