apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "256Mi"
              cpu: "50m"
            limits:
              memory: "512Mi"
              cpu: "100m"
          volumeMounts:
            - name: grafana-datasource
              mountPath: "/etc/grafana/provisioning/datasources"
              readOnly: true
            - name: spendingbetter-crt
              mountPath: "/etc/crt"
              readOnly: true
            - name: spendingbetter-key
              mountPath: "/etc/ssl_certs_key"
              readOnly: true
          env:
            - name: GF_AUTH_ANONYMOUS_ENABLED
              value: "true"
            - name: GF_AUTH_ANONYMOUS_ORG_ROLE
              value: Admin
            - name: GF_SERVER_DOMAIN
              value: spendingbetter.com
            - name: GF_SERVER_ROOT_URL
              value: https://spendingbetter.com/grafana
#            - name: GF_SERVER_PROTOCOL
#              value: https
            - name: GF_SERVER_SERVE_FROM_SUB_PATH
              value: "true"

            - name: GF_AUTH_GOOGLE_ENABLED
              value: "true"
            - name: GF_AUTH_GOOGLE_ALLOW_SIGN_UP
              value: "true"
            - name: GF_AUTH_GOOGLE_AUTO_LOGIN
              value: "true"
            - name: GF_AUTH_GOOGLE_CLIENT_ID
              value: client
            - name: GF_AUTH_GOOGLE_CLIENT_SECRET
              value: secret
            - name: GF_AUTH_GOOGLE_SCOPES
              value: openid email profile
            - name: GF_AUTH_GOOGLE_AUTH_URL
              value: https://accounts.google.com/o/oauth2/v2/auth
            - name: GF_AUTH_GOOGLE_TOKEN_URL
              value: https://oauth2.googleapis.com/token
            - name: GF_AUTH_GOOGLE_API_URL
              value: https://openidconnect.googleapis.com/v1/userinfo
            - name: GF_AUTH_GOOGLE_ALLOWED_DOMAINS
              value: spendingbetter.com
            - name: GF_AUTH_GOOGLE_HOSTED_DOMAIN
              value: spendingbetter.com
            - name: GF_AUTH_GOOGLE_USE_PKCE
              value: "true"
#            - name: GF_SERVER_CERT_FILE
#              value: /etc/crt/www.spendingbetter.com.crt
#            - name: GF_SERVER_CERT_KEY
#              value: /etc/ssl_certs_key/www.spendingbetter.com.key
          ports:
            - containerPort: 3000
      volumes:
        - name: grafana-datasource
          configMap:
            name: grafana-datasource
            items:
              - key: grafana-datasource.yaml
                path: datasource.yaml
        - name: spendingbetter-crt
          secret:
            secretName: spendingbetter-crt
        - name: spendingbetter-key
          secret:
            secretName: spendingbetter-key
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  ports:
    - port: 3000
  selector:
    app: grafana
