apiVersion: v1
kind: Secret
metadata:
  name: secrets
type: Opaque
data:
  KEYSTORE_PASSWORD: Q2VydDIwITk=
  CLIENT_ID: NjQ2MzcwMzcwODExLWxoMmRya2QxNG91dHVqbzIzcTAxamRnajVrN3UzOGdwLmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29tCg==
  CLIENT_SECRET: emxsYnFmd2N0T0htVnc1WEdJblRucnZYCg==