management:
    endpoints:
        web:
            exposure:
                include: '*'
            cors:
                allowed-origins: '*'
                allow-credentials: false
opentracing:
    spring:
        web:
            skip-pattern: "/actuator.*|/api-docs.*|/swagger.*|.*\\.png|.*\\.css|.*\\.js|.*\\.html|/favicon.ico|/hystrix.stream"
security:
    oauth2:
        resource:
            jwk:
                key-set-uri: https://spendingbetter.com/.well-known/jwks.json
spring:
    sleuth:
        baggage:
            remote-fields:
                - requestId
            correlation-fields:
                - requestId
---
spring:
    config:
        activate:
            on-profile: consul
        import: consul:${consul_url:localhost:8500}
    cloud:
        consul:
            config:
                fail-fast: ${FAIL_FAST:true}
                format: yaml
    autoconfigure:
        exclude: org.springframework.cloud.consul.config.ConsulConfigAutoConfiguration
